apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: books-client-api-app
  name: books-client-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
        app: books-client-api-app
  template:
    metadata:
        labels:
            app: books-client-api-app
    spec:
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: books-pvc
      containers:
      - name: books-client-api-app
        image: books-manager-app:latest
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5040
        volumeMounts:
        - name: data-storage
          mountPath: /booksfrontend/src/mount
#        command: ["python3", "../main.py"]
